# Generated by Django 2.2 on 2022-06-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
