# Generated by Django 2.2 on 2022-06-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20220603_1055'),
        ('orders', '0003_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_order_details', to='catalog.Size'),
        ),
    ]
