# Generated by Django 2.2 on 2022-05-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='price',
            name='title',
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_type_prices', to='catalog.PriceType'),
        ),
    ]
