# Generated by Django 2.2 on 2022-06-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_subategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories', verbose_name='image')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='catalog.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Subategory',
        ),
    ]
