# Generated by Django 2.2 on 2022-06-02 07:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
