# Generated by Django 2.2 on 2022-06-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
