# Generated by Django 2.2 on 2022-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220603_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(default='S', related_name='size_products', to='catalog.Size'),
        ),
    ]
