# Generated by Django 2.2 on 2022-06-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20220603_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='size_products', to='catalog.Size'),
        ),
    ]
