# Generated by Django 2.2 on 2022-05-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='PageInLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('position', models.CharField(choices=[('left', 'картинка слева'), ('right', 'картинка справа')], max_length=255, verbose_name='position')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_page_items', to='main.Page')),
            ],
        ),
    ]
