# Generated by Django 2.2 on 2022-05-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinline',
            name='title',
            field=models.CharField(default='title', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
