# Generated by Django 2.2 on 2022-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220531_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('image', models.ImageField(upload_to='slider', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('button_text', models.CharField(max_length=255, verbose_name='button_text')),
                ('button_link', models.URLField(verbose_name='button_link')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
